[General]
__userfile__=true
icon_theme=WhiteSur-macOS
palette_override=false
single_click_activate=false
theme=kvantum-macos
tool_button_style=ToolButtonTextBesideIcon

[Qt]
doubleClickInterval=400
font="Inter,12,-1,5,50,0,0,0,0,0"
style=kvantum
wheelScrollLines=3

[Screensaver]
lock_command=@HOME@/.local/share/macos-theme/macos-lock
