[General]
__userfile__=true
panels=panel1
iconTheme=Papirus-Light

[fancymenu]
ownIcon=true
alignment=Left
autoSel=true
autoSelDelay=150
filterClear=true
icon=@HOME@/.local/share/macos-theme/apple-menu-dark.svg
showText=false
type=fancymenu

[panel1]
alignment=1
desktop=0
hidable=false
iconSize=18
lineCount=1
panelSize=30
plugins=statusnotifier, tray, bellstatus, batstatus, btstatus, wifistatus, soundstatus, spotlight, nclock
position=Top
reserve-space=true
width=40
width-percent=true
hide-on-overlap=false
visible-margin=false
animation-duration=200
show-delay=150
background-color=#f2f2f2
opacity=100
font-color=#1d1d1f

[spacer]
alignment=Left
expandable=true
type=spacer
spaceType=invisible

[statusnotifier]
alignment=Right
type=statusnotifier
autoHideList=lubuntu-update, qlipper
hideList=nm-tray, blueman, lxqt-powermanagement, lxqt-notificationd

[tray]
alignment=Right
type=tray

[volume]
alignment=Right
device=0
type=volume

[worldclock]
alignment=Right
customFormat=ddd d MMM  h:mm AP
formatType=custom
showWeekNumber=false
type=worldclock
useAdvancedManualFormat=true

[spotlight]
type=customcommand
alignment=Right
icon=@HOME@/.local/share/icons/WhiteSur/actions/symbolic/system-search-symbolic.svg
click=@HOME@/.local/share/macos-theme/spotlight
tooltip=Spotlight
command=
text=
repeat=false

[nclock]
type=customcommand
alignment=Right
command=@HOME@/.local/share/macos-theme/notification-center-clock
runWithBash=false
repeat=true
repeatTimer=1
outputFormat=text
click=@HOME@/.local/share/macos-theme/notification-center
tooltip=
font="Inter,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
maxWidth=400

[btstatus]
type=customcommand
alignment=Right
command=@HOME@/.local/share/macos-theme/status-icon bluetooth
runWithBash=false
repeat=true
repeatTimer=5
outputFormat=1
click=@HOME@/.local/share/macos-theme/status-menu bluetooth
tooltip=
maxWidth=40

[wifistatus]
type=customcommand
alignment=Right
command=@HOME@/.local/share/macos-theme/status-icon wifi
runWithBash=false
repeat=true
repeatTimer=5
outputFormat=1
click=@HOME@/.local/share/macos-theme/status-menu wifi
tooltip=
maxWidth=40

[soundstatus]
type=customcommand
alignment=Right
command=@HOME@/.local/share/macos-theme/status-icon sound
runWithBash=false
repeat=true
repeatTimer=2
outputFormat=1
click=@HOME@/.local/share/macos-theme/status-menu sound
wheelUp=wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+
wheelDown=wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
tooltip=
maxWidth=40

[batstatus]
type=customcommand
alignment=Right
command=@HOME@/.local/share/macos-theme/status-icon battery
runWithBash=false
repeat=true
repeatTimer=10
outputFormat=1
click=@HOME@/.local/share/macos-theme/status-menu battery
tooltip=
maxWidth=40

[bellstatus]
type=customcommand
alignment=Right
command=@HOME@/.local/share/macos-theme/status-icon notifications
runWithBash=false
repeat=true
repeatTimer=3
outputFormat=1
click=@HOME@/.local/share/macos-theme/status-menu notifications
tooltip=
maxWidth=40
